services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=symfony
      - MARIADB_DATABASE=symfony
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/bitnami/mariadb

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/bash", "-c"]
    command: [
      "/usr/bin/wait-for-it mariadb:3306 --timeout=30 --strict -- echo 'MariaDB is up.' &&
       composer install --no-interaction &&
       php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration &&
       apache2-foreground"
    ]
    ports:
      - '8000:80'
    environment:
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=symfony
      - SYMFONY_DATABASE_NAME=symfony
    volumes:
      - './app:/var/www/html'
      - './app/vendor:/var/www/html/vendor'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
